### ISSUE TITLE
yolox initial weight

### ISSUE THREAD

**Issue by spy001s** [yuto3o/yolox#11]
hello
thanks for your coding
which initial wieght we use in the running code with yolox network at cfg files?

**Comment by spy001s** [comment]
and how can i download the yolov4_tiny.h5 files?

**Comment by yuto3o** [comment]
1. You can download them from https://github.com/AlexeyAB/darknet/releases or https://pjreddie.com/darknet/yolo/.
2. And them convert them into .h5 file with our code.
3. Please read Readme.md first.

**Comment by spy001s** [comment]
i'm download it ,but it dosen't convert to h5 formats
