### ISSUE TITLE
IndexError: index 3 is out of bounds for axis 0 with size 3

### ISSUE THREAD

**Issue by amirhosseinghdv** [yuto3o/yolox#14]
@yuto3o 
Thank you for your great code. I did everything as explained, but while training i keep receiving the error:  "IndexError: index 3 is out of bounds for axis 0 with size 3" after some train steps. what do you think could be the problem? Thanks.

**Comment by yuto3o** [comment]
Maybe there are some mistakes in the data.

**Comment by amirhosseinghdv** [comment]
@yuto3o 
Thankfully i could manage to find the issue with my data, but unfortunately now while training, as mentioned by other users, for all epochs i get the massage "AP not improved from 0.00%" and the best loss is 12. it happens whether using pre-trained weights or not.  i could not find the solution by reading those discussions. i really appreciate it if you could help.

**Comment by yuto3o** [comment]
It is not a simple question. Instead of using default config, please try more hyperparameters.

**Comment by amirhosseinghdv** [comment]
I believe this is not the point. whatever the hyperparameters, the AP should not be exactly equal to 0.00 for all epochs.  while using your train.py code, the last two line (if __name__ == '__main__':) gets me an error so i took the components of the main function out of it and run them in different cells. could it be the problem? cause i have noticed that in core.model.one_stage.yolov4 code, there is the same part with (if __name__ == '__main__':) that may not be executed this way.

**Comment by amirhosseinghdv** [comment]
@yuto3o 
Thanks again, i changed some hyperparameters and could reach AP of 35%, but i had reached AP of 60% using Alexey AB repository by changing it's config according to it's guiding based on number of classes with the same amount of data, but your code's configs file is different and i wasn't able to do so. would you please provide some help on how to set the hyperparameters according to our number of classes in order to achieve the best result with your code.
Thanks

**Comment by yuto3o** [comment]
Yep, this repo does not guarantee the same behavior as Alexey's repo do. Maybe you can use hyperparameter searching toolkit like https://github.com/scikit-optimize/scikit-optimize.
