### ISSUE TITLE
Handling non-square images

### ISSUE THREAD

**Issue by RatkoFri** [yuto3o/yolox#18]
Greetings, 

I am using YOLOv4_tiny to detect objects on images in the shape 2704x1520. How to configure yaml cfg files? 

When I am using the images in the shape 2704x1520, the Keras throws a dimension mismatch error. 

Ratko

**Comment by yuto3o** [comment]
do nothing, or keep the shape of images could be divisible by all strides in your cfg file.

**Comment by RatkoFri** [comment]
Thanks.
