### ISSUE TITLE
Does your code support all the functions of yolov4 and can it train normally ?

### ISSUE THREAD

**Issue by zcdliuwei** [yuto3o/yolox#2]

**Comment by yuto3o** [comment]
- Part of the functions is supported.
- It can be trained normally.

**Comment by zcdliuwei** [comment]
I want to ask for your advice. I want to identify the bottles in the trash can. The real image is about this:

![20200611112928_B_Q](https://user-images.githubusercontent.com/36565076/85197565-61d09980-b314-11ea-95ea-64b2beaa02fa.jpg)

![20200611112934_B_Q](https://user-images.githubusercontent.com/36565076/85197566-65fcb700-b314-11ea-9b9c-346464d64ce3.jpg)

![20200611113139_B_Q](https://user-images.githubusercontent.com/36565076/85197567-66954d80-b314-11ea-87c3-2173fca86c2e.jpg)

The most complex part of this scene is the dense shielding and stacking of bottles. Our purpose is to tell the customer who threw the bottle what kind of bottle he threw in, and it's better to return the location information of the bottle at the bottom of the trash can. At present, I use Yolo series for testing, and the effect is always unsatisfactory.

I want to know does you have any suggestions to improve the detection and classification ability in this scenario?

Much obliged for your assistance.

**Comment by yuto3o** [comment]
More effective training data in this scene is necessary.
