### ISSUE TITLE
train.py not working 

### ISSUE THREAD

**Issue by Merwanski** [yuto3o/yolox#4]
Hey, 

I am currently having a problem with train.py

After some debugging I found that the error occurs at the following line: 
>> model.fit(train_dataset, steps_per_epoch=len(train_dataset), epochs=warmup_epochs, callbacks=warmup_callback)

and the Error message obtained is the following:
 self._value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

any idea what is causing this? or how to investigate further where the error is comming from? 
Thank you in advance

Merwan

**Comment by yuto3o** [comment]
we use tensorflow 2.1 to test our code.

**Comment by Merwanski** [comment]
I am using TensorFlow 2.0.2 and I was able to solve the issue using the model.fit_generator instead of the model.fit

**Comment by yuto3o** [comment]
Such similar issue will help you.
https://github.com/tensorflow/tensorflow/issues/38032

**Comment by Merwanski** [comment]
Thank you 🙂

Merwan
________________________________
De : yuyang <notifications@github.com>
Envoyé : jeudi 2 juillet 2020 09:04
À : yuto3o/yolox <yolox@noreply.github.com>
Cc : Merwanski <merwan.birem@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [yuto3o/yolox] train.py not working (#4)


Such similar issue will help you.
tensorflow/tensorflow#38032<https://github.com/tensorflow/tensorflow/issues/38032>
