### ISSUE TITLE
通过关闭cfg中的数据增强手段和减小epch大小  确实加快了训练速度  但map值却一直没有上涨

### ISSUE THREAD

**Issue by VYXUOF** [yuto3o/yolox#7]
大佬 ，感谢你上期的回答，但是现在这个问题导致训练的效率没有提升，如果可以的话能不能加一下你的微信或qq向你学习一下代码和调参，我现在很想把yolov4-tiny吃透

**Comment by VYXUOF** [comment]
我使用的是coco这个数据集，现在最高停留在7.4%，和给出的40%相差甚远，已经卡了几天了，希望能够得到你的帮助

**Comment by yuto3o** [comment]
我主页上的邮箱可以搜到我的QQ。
因为算力问题，其实我也没有在COCO上做过实验，但是讲道理不会这么低，请问你是从0开始训练的吗？没有载入预训练？

**Comment by yuto3o** [comment]
另外，有类似问题请把代码更到最新，可能是优化策略导致的。
