### ISSUE TITLE
Transform Model to Real_Time: Serialize Model

### ISSUE THREAD

**Issue by Juan-glitch** [yuto3o/yolox#8]
# It is possible to Save the trained model in tensorflow format for real_time use with OpenCV-OpenVino?
As far as I know Tf.Keras runs on top of TensorFlow and it doesn´t create the graph to run this way.

While the detail of graph and session is outside of the scope of this question, how can we deploy it woth OpenCV module:
 can still use the following code when deploying your model to be accessible during scheduled sessions.
This is an example. In darknet models it was quite easy and it was compatible with OpenCV. I am not shure if this way it is possible.

## Load a model imported from Tensorflow
tensorflowNet = cv2.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'graph.pbtxt')
#
To finish, the rest of the code and they it is structures is impecable. 
P.D:
Thank you a lot for all the help to make it easier for us to keep learning from this incredible technology!

**Comment by yuto3o** [comment]
We use tensorflow 2 and it doesn't support 'freeze inference graph' feature any more. Thus, tensorflow 1.15 or tf.compat.v1 may help you freeze your graph and use opencv api.
